In [17]:
import numpy as np
import pandas as pd

In [18]:
students=np.array(["Kashi","Lavi","Sid","Jack","Rocky","Siya","Ram","Reena","Koshik","Komal","Krati","Priya","Gauri","Kanha","Shiv"])
subjects="Python","CyberSecurity","DataScience","Cloudcomputing","Ai"

In [19]:
len(students),len(subjects)

(15, 5)

In [20]:
marks=np.array([
    [61,78,89,90,89],
    [95,96,97,98,99],
    [46,37,28,38,45],
    [87,35,56,47,67],
    [27,35,37,44,67],
    [61,78,89,90,34],
    [95,76,87,38,33],
    [26,37,28,38,22],
    [87,35,56,47,78],
    [27,35,37,44,33],
    [61,78,89,90,67],
    [95,76,87,38,67],
    [26,37,28,38,32],
    [87,35,56,47,78],
    [27,35,37,44,45],
])
print(marks)


[[61 78 89 90 89]
 [95 96 97 98 99]
 [46 37 28 38 45]
 [87 35 56 47 67]
 [27 35 37 44 67]
 [61 78 89 90 34]
 [95 76 87 38 33]
 [26 37 28 38 22]
 [87 35 56 47 78]
 [27 35 37 44 33]
 [61 78 89 90 67]
 [95 76 87 38 67]
 [26 37 28 38 32]
 [87 35 56 47 78]
 [27 35 37 44 45]]


In [21]:
#Pandas DataFrame for tabular representation of Data
df=pd.DataFrame(marks,index=(students),columns=(subjects))
dfs

,Python,CyberSecurity,DataScience,Cloudcomputing,Ai
Kashi,61,78,89,90,89
Lavi,95,96,97,98,99
Sid,46,37,28,38,45
Jack,87,35,56,47,67
Rocky,27,35,37,44,67
Siya,61,78,89,90,34
Ram,95,76,87,38,33
Reena,26,37,28,38,22
Koshik,87,35,56,47,78
Komal,27,35,37,44,33


In [22]:
#Total Marks of students out of 500
total_marks=np.sum(marks,axis=1)
print(total_marks)

[407 485 194 292 210 352 329 151 303 176 385 363 161 303 188]


In [23]:
# Student Ranking 
rank_indices = np.argsort(-total_marks)

print("----- Student Ranking -----")

for rank, index in enumerate(rank_indices, start=1):
    print(f"Rank {rank}: {students[index]} - Total Marks = {total_marks[index]}")

----- Student Ranking -----
Rank 1: Lavi - Total Marks = 485
Rank 2: Kashi - Total Marks = 407
Rank 3: Krati - Total Marks = 385
Rank 4: Priya - Total Marks = 363
Rank 5: Siya - Total Marks = 352
Rank 6: Ram - Total Marks = 329
Rank 7: Koshik - Total Marks = 303
Rank 8: Kanha - Total Marks = 303
Rank 9: Jack - Total Marks = 292
Rank 10: Rocky - Total Marks = 210
Rank 11: Sid - Total Marks = 194
Rank 12: Shiv - Total Marks = 188
Rank 13: Komal - Total Marks = 176
Rank 14: Gauri - Total Marks = 161
Rank 15: Reena - Total Marks = 151


In [24]:
# Average Marks of Studenta
average_marks=np.mean(marks,axis=1)
print(average_marks)

[81.4 97.  38.8 58.4 42.  70.4 65.8 30.2 60.6 35.2 77.  72.6 32.2 60.6
 37.6]


In [25]:
#Percentage Analysis
percentage=(total_marks/500)*100
print(percentage)
highest_percentage_index=np.argmax(percentage)
highest_percentage=percentage[highest_percentage_index]
print(highest_percentage)
lowest_percentage_index=np.argmin(percentage)
lowest_percentage=percentage[lowest_percentage_index]
print(lowest_percentage)

[81.4 97.  38.8 58.4 42.  70.4 65.8 30.2 60.6 35.2 77.  72.6 32.2 60.6
 37.6]
97.0
30.2


In [26]:
a=np.where(percentage>=40,"Pass","Fail")
print(a)

['Pass' 'Pass' 'Fail' 'Pass' 'Pass' 'Pass' 'Pass' 'Fail' 'Pass' 'Fail'
 'Pass' 'Pass' 'Fail' 'Pass' 'Fail']


In [27]:
#Highest Marks Calculation
highest_index=np.argmax(total_marks)
print("Rollno:",highest_index)
h_name=students[highest_index]
print("Name:",h_name)
print("Highest Marks:",total_marks[highest_index],"out of 500")
print("Percentage: ",highest_percentage)
result=a[highest_index]
print("result:",result)

Rollno: 1
Name: Lavi
Highest Marks: 485 out of 500
Percentage:  97.0
result: Pass


In [28]:
#Lowest Marks Calculation
lowest_index=np.argmin(total_marks)
print("Rollno:",lowest_index)
l_name=students[lowest_index]
print("Name:",l_name)
print("Lowest Marks:",total_marks[lowest_index],"out of 500")
print("Percentage:",lowest_percentage)
result=a[lowest_index]
print("result:",result)

Rollno: 7
Name: Reena
Lowest Marks: 151 out of 500
Percentage: 30.2
result: Fail


In [29]:
#Subjectwise Analysis
subject_average=np.mean(marks,axis=0)
print(subject_average)

[60.53333333 53.53333333 60.06666667 55.4        57.06666667]


In [30]:
while True:
    
    search_name=input("enter student name:").capitalize()
    if search_name in students:
        student_index=np.where(students==search_name)[0][0]
        print("Student name:",students[student_index])
        print("Marks:",marks[student_index])
        print("Total Marks:",total_marks[student_index])
        print("Percentage:",percentage[student_index])
        print("Result:",a[student_index])
        
        # Ranking System
        rank_indices = np.argsort(-total_marks)

        student_rank = np.where(rank_indices == student_index)[0][0]+1
        print("Rank:", student_rank)
        
    else:
        print("Student Name Not Found")

    again=input("Do you want to search again ? (Yes/No):").capitalize()
    if again!="Yes":
        print("Thanks")
        break


enter student name: lavi


Student name: Lavi
Marks: [95 96 97 98 99]
Total Marks: 485
Percentage: 97.0
Result: Pass
Rank: 1


Do you want to search again ? (Yes/No): yes
enter student name: kashi


Student name: Kashi
Marks: [61 78 89 90 89]
Total Marks: 407
Percentage: 81.39999999999999
Result: Pass
Rank: 2


Do you want to search again ? (Yes/No): no


Thanks
